name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Configure project with CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build project
        run: |
          cd build
          cmake --build .

      - name: Show build directory contents
        run: ls -l build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
